version: '3.7'
services:
  mysql:
    image: ghcr.io/elevatodigital/docker-development-environments/lamp-7-mysql:latest
    build:
      context: '.'
      dockerfile: 'DockerfileMysql'
    ports:
      - "3307:3306"
    volumes:
      - "./conf/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      #- "./mysql-on-init:/docker-entrypoint-initdb.d"
  web:
    image: ghcr.io/elevatodigital/docker-development-environments/lamp-7-web:latest
    build:
      context: '.'
      dockerfile: 'DockerfileWeb'
    ports:
      - "8081:80"
    volumes:
      - "./conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./conf/supervisor:/etc/supervisor/conf.d"
      - "./conf/cron/crontab.txt:/etc/cron.d/crontab"
      #- "./src:/var/www/vhosts/myvhost"
      - "./conf/gelf/gelf.key:/root/.ssh/gelf.key.mounted"
      #- "./deploy.php:/var/www/vhosts/myvhost/private/deploy.php"
      #- "./deployer.phar:/var/www/vhosts/myvhost/private/deployer.phar"
    links:
      - 'mysql:mysql'
